export interface MapData {
  id: string;
  value: number;
  name: string;
}

export const chartData = [
  { id: "US-AL", value: 0, name: "Alabama" },
  { id: "US-AK", value: 0, name: "Alaska" },
  { id: "US-AZ", value: 0, name: "Arizona" },
  { id: "US-AR", value: 0, name: "Arkansas" },
  { id: "US-CA", value: 0, name: "California" },
  { id: "US-CO", value: 0, name: "Colorado" },
  { id: "US-CT", value: 0, name: "Connecticut" },
  { id: "US-DE", value: 0, name: "Delaware" },
  { id: "US-FL", value: 0, name: "Florida" },
  { id: "US-GA", value: 0, name: "Georgia" },
  { id: "US-HI", value: 0, name: "Hawaii" },
  { id: "US-ID", value: 0, name: "Idaho" },
  { id: "US-IL", value: 0, name: "Illinois" },
  { id: "US-IN", value: 0, name: "Indiana" },
  { id: "US-IA", value: 0, name: "Iowa" },
  { id: "US-KS", value: 0, name: "Kansas" },
  { id: "US-KY", value: 0, name: "Kentucky" },
  { id: "US-LA", value: 0, name: "Louisiana" },
  { id: "US-ME", value: 0, name: "Maine" },
  { id: "US-MD", value: 0, name: "Maryland" },
  { id: "US-MA", value: 0, name: "Massachusetts" },
  { id: "US-MI", value: 0, name: "Michigan" },
  { id: "US-MN", value: 0, name: "Minnesota" },
  { id: "US-MS", value: 0, name: "Mississippi" },
  { id: "US-MO", value: 0, name: "Missouri" },
  { id: "US-MT", value: 0, name: "Montana" },
  { id: "US-NE", value: 0, name: "Nebraska" },
  { id: "US-NV", value: 0, name: "Nevada" },
  { id: "US-NH", value: 0, name: "New Hampshire" },
  { id: "US-NJ", value: 0, name: "New Jersey" },
  { id: "US-NM", value: 0, name: "New Mexico" },
  { id: "US-NY", value: 0, name: "New York" },
  { id: "US-NC", value: 0, name: "North Carolina" },
  { id: "US-ND", value: 0, name: "North Dakota" },
  { id: "US-OH", value: 0, name: "Ohio" },
  { id: "US-OK", value: 0, name: "Oklahoma" },
  { id: "US-OR", value: 0, name: "Oregon" },
  { id: "US-PA", value: 0, name: "Pennsylvania" },
  { id: "US-RI", value: 0, name: "Rhode Island" },
  { id: "US-SC", value: 0, name: "South Carolina" },
  { id: "US-SD", value: 0, name: "South Dakota" },
  { id: "US-TN", value: 0, name: "Tennessee" },
  { id: "US-TX", value: 0, name: "Texas" },
  { id: "US-UT", value: 0, name: "Utah" },
  { id: "US-VT", value: 0, name: "Vermont" },
  { id: "US-VA", value: 0, name: "Virginia" },
  { id: "US-WA", value: 0, name: "Washington" },
  { id: "US-WV", value: 0, name: "West Virginia" },
  { id: "US-WI", value: 0, name: "Wisconsin" },
  { id: "US-WY", value: 0, name: "Wyoming" },
];

export default chartData;
